"""Add sensor tables

Revision ID: 3943557b0bca
Revises: b94ab8372f48
Create Date: 2025-06-07 15:35:12.445690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3943557b0bca'
down_revision = 'b94ab8372f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_co2_temp_hum_ext',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueCO2', sa.Integer(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueHum', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_co2_temp_hum_int',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueCO2', sa.Integer(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueHum', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_light_ext',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_light_int',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_sm_temp_ec_1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueSM', sa.Double(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueEC', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_sm_temp_ec_2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueSM', sa.Double(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueEC', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_sm_temp_ec_3',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueSM', sa.Double(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueEC', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_sm_temp_ec_4',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('valueSM', sa.Double(), nullable=False),
    sa.Column('valueTemp', sa.Double(), nullable=False),
    sa.Column('valueEC', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_sm_temp_ec_4')
    op.drop_table('sensor_sm_temp_ec_3')
    op.drop_table('sensor_sm_temp_ec_2')
    op.drop_table('sensor_sm_temp_ec_1')
    op.drop_table('sensor_light_int')
    op.drop_table('sensor_light_ext')
    op.drop_table('sensor_co2_temp_hum_int')
    op.drop_table('sensor_co2_temp_hum_ext')
    # ### end Alembic commands ###
